--- #YAML:1.0
name: Net-Address-IPv4-Local
version: 0.10
author:
  - Julian Mehnle <julian@mehnle.net>
abstract: |-
  A class for discovering the local system's IP
  address
license: perl
requires:
  IO::Socket::INET: 0
  perl: 0
provides:
  Net::Address::IPv4::Local:
    file: lib/Net/Address/IPv4/Local.pm
    version: 0.10
  Net::Address::IPv4::Local::Error:
    file: lib/Net/Address/IPv4/Local.pm
    version: 0.10
generated_by: Module::Build version 0.26
